# config/routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Redirige vers la page de login
index:
    path: /
    controller: App\Controller\SecurityController::redirectToLogin